### ISSUE TITLE
RingsDB: Can't access personel LOTR LCG decklist and deckbuilder

### ISSUE THREAD

**Issue by LordSnappyPants** [seastan/ringsdb#129]
Can't build a new deck or view my old decks on RingsDB. I get the following prompt after some buffering "The server encountered an error 500. Please report it on GitHub"

**Comment by kasperkronborg** [comment]
+1

**Comment by recor-boop** [comment]
i have the same problem.. :/

**Comment by kasperkronborg** [comment]
It seems to be fixed now.

**Comment by recor-boop** [comment]
Thank you a lot 🙏🏽

Téléchargez Outlook pour iOS<https://aka.ms/o0ukef>
________________________________
De : Kasper Kronborg ***@***.***>
Envoyé : Wednesday, August 3, 2022 11:12:15 PM
À : seastan/ringsdb ***@***.***>
Cc : recor-boop ***@***.***>; Comment ***@***.***>
Objet : Re: [seastan/ringsdb] RingsDB: Can't access personel LOTR LCG decklist and deckbuilder (Issue #129)


It seems to be fixed now.

**Comment by recor-boop** [comment]
Is there possibly a general slowing down since a few days ?
It tends to happens with me it seems.

Thanks for the good support :)

Téléchargez Outlook pour iOS<https://aka.ms/o0ukef>
________________________________
De : yannick degrande ***@***.***>
Envoyé : Wednesday, August 3, 2022 11:13:19 PM
À : seastan/ringsdb ***@***.***>; seastan/ringsdb ***@***.***>
Cc : Comment ***@***.***>
Objet : Re: [seastan/ringsdb] RingsDB: Can't access personel LOTR LCG decklist and deckbuilder (Issue #129)

Thank you a lot 🙏🏽

Téléchargez Outlook pour iOS<https://aka.ms/o0ukef>
________________________________
De : Kasper Kronborg ***@***.***>
Envoyé : Wednesday, August 3, 2022 11:12:15 PM
À : seastan/ringsdb ***@***.***>
Cc : recor-boop ***@***.***>; Comment ***@***.***>
Objet : Re: [seastan/ringsdb] RingsDB: Can't access personel LOTR LCG decklist and deckbuilder (Issue #129)


It seems to be fixed now.

**Comment by kasperkronborg** [comment]
I have also noticed a degradation in performance as of late. This is not a complaint since this is a completely free service, but just wanted to raise the issue if this was something that was effected by some new code.
