### ISSUE TITLE
Allow decks to search cards by ID

### ISSUE THREAD

**Issue by lebigot** [seastan/ringsdb#21]
The [card search](https://ringsdb.com/search) allows one to enter a numeric ID and find a card (e.g. 04110, which means set #04, card #110). This is very useful for players of non-English editions.

Now, it would be great if the card search in the deck builder allowed the same thing. Otherwise, it is really hard to save a non-English real deck to RingsDB, which limits its usage. Or maybe I missed a feature that would help with this?

**Comment by seastan** [comment]
I'm confused as to how you are benefiting by using the code.

Let's say you have the card La Grande Chasse. It came in the Fate of Wilderland Pack. How are you determining it's code?

**Comment by lebigot** [comment]
The card number is written on the card itself, and the sets are simply ordered with increasing numbers, so it's not hard to construct the card ID.

**Comment by seastan** [comment]
The sets numbers are not necessarily defined that way. For example:

City of Corsairs is pack 12.
Sands of Harad (the next product in progression) is pack 14.
Over Hill and Under Hill (released long before either pack) is pack 131.

Pack numbers are set arbitrarily because there was never any intention for users to interact with them in any way.

**Comment by lebigot** [comment]
So a listing of the sets IDs would help with the problem of building decks (and finding cards) based on non-English cards?

**Comment by seastan** [comment]
That would still require knowing the English name for the pack, right?

Taking for example again La Grande Chasse from the Fate of Wilderland pack. If you type in the ringsdb search "e:FoW", the cards for Fate of Wilderland come up, and it easy from there to spot La Grande Chasse from the list of 10 cards even without knowing the English name. This seems easier than looking at a big table of set codes for each card?

In fact, it seems like it would be quicker to assemble a deck from another language if you just use the filter buttons. So select "lore" and "event" and type in the search bar "o:3" and then look through the few 3-cost lore events.

**Comment by lebigot** [comment]
Good point. This seems like a good alternative to the "find cards by ID" problem.

Now, finding the set of a random non-English card is a bit cumbersome: we only see the *cycle* icon, on the cards.

Ideally cards could be found by name, including non-English names. I can probably relatively quickly build a file mapping an expansion name and a card number to the French card name for most cards (core, deluxe, saga, and cycles, up to Ered Mithrin included, plus some Pods and Nightmare decks): let me know if this can help provide this functionality!

**Comment by seastan** [comment]
I have two questions about your proposal:

1. If I type in "La" in the search box, will the autocomplete dropdown show the English name "The Great Hunt" or will it show "La Grande Chasse"? Because I could see this being very confusing to English speakers either way. If I am searching for "Lay of Nimrodel" and I type "La", I do not want the dropdown to dozens of cards in every language that contain the letters "La".

2. If we do come up with a more user-friendly way to do this (and thank you for the offer to help), would you be committed to maintaining it indefinitely? Because it is already a lot of work to maintain the English database, and if you stop maintaining it in a year or two it will fall behind and I will be then dealing with people complaining about the outdated database.

**Comment by lebigot** [comment]
Good questions.

1. I thought I remember a card database that handled multiple languages, but I can't seem to find anything beyond https://scryfall.com/, which doesn't have any autocomplete dropdown, so I don't have an existing, working model.
  With the current card search, that looks for full substrings, typing a common French word like "la" would indeed be a problem.
  I can imagine two solutions: (1) restrict the search to matching the beginning of a card name only, and (2) have a language switch.

2. The answer is unfortunately no to "maintaining indefinitely", as I am not ready to enter card names one by one (I already have electronic data with the cards I mentioned, though, which represents a very large part of what was published in French so far). This would mean accepting that not all the cards are searchable in French (a disclaimer could be added).

Now, this seems complicated, and I think that non-English cards could be found easily enough _if cycles could be searched in the deck building tool too_ (like in the card search, with something like "c:SoM" for the Shadows of Mirkwood cycle). In fact, it is difficult to take a random card and find out its adventure pack, whereas the icon on the card indicates its cycle. Since there are not so many cycles, it's not too hard to remember them all in English.

So what do you think of the idea of bringing the nice cycle search from Search into Deckbuidling? That would make using the deckbuilder with non-English cards easier.

**Comment by seastan** [comment]
c:SoM is already supposed to be a function in the deckbuilder (See the dropdown under "Filter help"). The fact that it is not working is a bug, which has not been reported until now.

The filter does work for the card search however, so a current workaround would be to type the cycle acronym in the card search to determine the English name for the card.

https://ringsdb.com/cycle/SoM/list/name

**Comment by lebigot** [comment]
OK, thanks.

Let me close this issue and open a new one, then.
